// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// plotxyz
void plotxyz(NumericVector x, NumericVector y, NumericVector z, IntegerMatrix col, float size);
RcppExport SEXP _PointCloudViewer_plotxyz(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP colSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type col(colSEXP);
    Rcpp::traits::input_parameter< float >::type size(sizeSEXP);
    plotxyz(x, y, z, col, size);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PointCloudViewer_plotxyz", (DL_FUNC) &_PointCloudViewer_plotxyz, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_PointCloudViewer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
