# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

viewer <- function(df, detach, hnof) {
    invisible(.Call(`_lidRviewer_viewer`, df, detach, hnof))
}

