# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
plotxyz <- function(x, y, z, col, size = 2) {
    invisible(.Call(`_PointCloudViewer_plotxyz`, x, y, z, col, size))
}

